name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (Linux)
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      if: matrix.platform == 'ubuntu-latest'
    - name: Download font file
      run: |
        sudo mkdir -p assets/font
        cd assets/font
        sudo wget https://font.download/dl/font/roboto-mono.zip
        sudo unzip roboto-mono.zip
        sudo mv RobotoMono-Medium.ttf RobotoMono.ttf
      if: matrix.platform == 'ubuntu-latest'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
